const pujasData = [
  {
    title: 'Griha Pravesh Puja',
    slug: 'griha-pravesh-puja',
    badge: 'Housewarming',
    description: 'Complete Vastu Shanti, Navagraha Havan, and threshold purification ritual for a blessed, prosperous new home.',
    category: 'Griha Pravesh',
    duration: '3.5 Hours',
    panditsCount: '2 Pandits',
    startingPrice: 4100,
    samagriPrice: 1200,
    icon: '🪔',
    bgEmoji: '🏡',
    themeColor: 'amber',
    includesText: 'Complete Vastu & Navagraha Havan, Kalash Sthapana & threshold purification',
    checklist: [
      'Keep 2 clean brass plates/thalis and 2 cotton asanas (mats) ready.',
      'Pandit Ji will bring the complete 42-item havan samagri kit and dry herbs.',
      'Keep fresh cow milk (250 ml) and 5 seasonal fruits ready for prasad.',
    ],
  },
  {
    title: 'Maha Saptami & Chandi Path',
    slug: 'maha-saptami-chandi-path',
    badge: 'Festival Special',
    description: 'Durga Saptashati recitation, Pran Pratishtha, and traditional Kumari pujan invocation with sacred Chandi havan.',
    category: 'Festive & Saptami',
    duration: '4.0 Hours',
    panditsCount: '1-2 Pandits',
    startingPrice: 5100,
    samagriPrice: 1500,
    icon: '🔱',
    bgEmoji: '🌺',
    themeColor: 'orange',
    includesText: 'Durga Saptashati recitation, Pran Pratishtha, and traditional Kumari pujan',
    checklist: [
      'Red cloth for altar, fresh red hibiscus flowers, pure cow ghee (500g).',
      'Pandit brings authentic copper havan kund, sacred Chandi samagri and dry offerings.',
      'Panchamrit preparation (milk, curd, honey, sugar, ghee) kept ready before ritual.',
    ],
  },
  {
    title: 'Shri Satyanarayan Katha',
    slug: 'shri-satyanarayan-katha',
    badge: 'Family Auspiciousness',
    description: 'Full 5-chapter sacred katha recitation with Panchamrit pujan, aarti, and havan samapti for domestic prosperity.',
    category: 'Festive & Saptami',
    duration: '2.5 Hours',
    panditsCount: '1 Pandit',
    startingPrice: 2500,
    samagriPrice: 800,
    icon: '✨',
    bgEmoji: '✨',
    themeColor: 'yellow',
    includesText: 'Full 5-chapter katha recitation with Panchamrit pujan and havan samapti',
    checklist: [
      'Tulsi leaves, fresh bananas, wheat flour panjiri prasad, panchamrit.',
      'Chowki (low wooden table) with clean yellow cloth for Lord Satyanarayan altar.',
      'Fresh marigold garland, betel leaves (paan), and supari.',
    ],
  },
  {
    title: 'Mahamrityunjaya Jaap & Havan',
    slug: 'mahamrityunjaya-jaap-havan',
    badge: 'Health & Longevity',
    description: 'Vedic jaap with sacred Rudra Abhishek and healing yagna for health, recovery, and long life protection.',
    category: 'Havans & Yagnas',
    duration: '5.0 Hours',
    panditsCount: '3 Pandits',
    startingPrice: 7500,
    samagriPrice: 1800,
    icon: '🕉️',
    bgEmoji: '🔥',
    themeColor: 'purple',
    includesText: 'Vedic Rudra Sukta recitation, Bilva Patra Abhishek, and healing Ahutis',
    checklist: [
      'Gangajal, Bilva leaves, raw cow milk, honey, and sugarcane juice for holy Abhishek.',
      'Clean havan altar space prepared with cotton rugs.',
      'Black sesame seeds, guggal, dry fruits, and sacred wood provided by Pandit Ji.',
    ],
  },
  {
    title: 'Kaal Sarp Dosha & Navagraha Shanti',
    slug: 'kaal-sarp-dosha-navagraha-shanti',
    badge: 'Planetary Healing',
    description: 'Alleviates planetary afflictions and Rahu-Ketu dosha, removing life obstacles and restoring peace of mind.',
    category: 'Dosha Nivarana',
    duration: '3.0 Hours',
    panditsCount: '2 Pandits',
    startingPrice: 4800,
    samagriPrice: 1400,
    icon: '🪐',
    bgEmoji: '🪐',
    themeColor: 'indigo',
    includesText: '9 Graha Mandalam, Rahu-Ketu tarpana, and sacred silver serpent archana',
    checklist: [
      '9 varieties of grains (Navadhanya) and 9 colored cotton cloths.',
      'Purohit brings energized Rahu-Ketu yantra and sacred havan ingredients.',
      'Clean asanas for yajman and family members facing eastward.',
    ],
  },
  {
    title: 'Vastu Shanti & Bhoomi Pujan',
    slug: 'vastu-shanti-bhoomi-pujan',
    badge: 'Vastu Harmony',
    description: 'Purifies negative energies, harmonizes cosmic directions, and invokes Vastu Purusha for residential/commercial spaces.',
    category: 'Griha Pravesh',
    duration: '3.0 Hours',
    panditsCount: '2 Pandits',
    startingPrice: 4500,
    samagriPrice: 1300,
    icon: '🏡',
    bgEmoji: '🏛️',
    themeColor: 'amber',
    includesText: 'Vastu Purusha archana, Digbandhan, and Ishanya Kona sanctification',
    checklist: [
      'Copper kalash with fresh coconut and mango leaves.',
      'Vastu Yantra and 5 metals (Panchadhatu) for foundation/threshold placement.',
      'Pure Ganga jal and turmeric paste for sanctifying premises.',
    ],
  },
];

const panditsData = [
  {
    name: 'Pt. Rameshwar Sharma',
    initials: 'RS',
    gurukul: 'Varanasi Gurukul',
    experienceYears: 18,
    rating: 4.95,
    reviewsCount: 280,
    tradition: 'Shukla Yajurveda',
    languages: ['Hindi', 'Sanskrit', 'Bhojpuri'],
    includes: 'Complete Vastu & Havan Vidhi',
    dakshina: 4100,
    avatarBg: 'orange',
    phone: '+91 98101 23456',
    verified: true,
  },
  {
    name: 'Pt. Devendra Shastri',
    initials: 'DS',
    gurukul: 'Sampurnanand Sanskrit Vishwavidyalaya',
    experienceYears: 14,
    rating: 4.9,
    reviewsCount: 194,
    tradition: 'Rigvedic Sampradaya',
    languages: ['Hindi', 'Sanskrit', 'English'],
    includes: 'Kundali Muhurat Verification',
    dakshina: 3800,
    avatarBg: 'amber',
    phone: '+91 98202 34567',
    verified: true,
  },
  {
    name: 'Pt. Ananda Bhattacharya',
    initials: 'AB',
    gurukul: 'Nabadwip Scholar Lineage',
    experienceYears: 16,
    rating: 4.88,
    reviewsCount: 162,
    tradition: 'Vedic & Bengali Purohit',
    languages: ['Bengali', 'Hindi', 'Sanskrit'],
    includes: 'Traditional Saptami & Griha Pujan',
    dakshina: 4500,
    avatarBg: 'red',
    phone: '+91 98303 45678',
    verified: true,
  },
  {
    name: 'Pt. Vidyadhar Joshi',
    initials: 'VJ',
    gurukul: 'Ujjain Sandipani Ashram',
    experienceYears: 21,
    rating: 4.97,
    reviewsCount: 340,
    tradition: 'Atharvaveda & Krishna Yajurveda',
    languages: ['Hindi', 'Marathi', 'Sanskrit'],
    includes: 'Navagraha & Kaal Sarp Vidhan Expert',
    dakshina: 4800,
    avatarBg: 'emerald',
    phone: '+91 98404 56789',
    verified: true,
  },
];

module.exports = { pujasData, panditsData };
